ALTER TABLE meals ADD COLUMN protein REAL DEFAULT 0;
ALTER TABLE meals ADD COLUMN carbs REAL DEFAULT 0;
ALTER TABLE meals ADD COLUMN fat REAL DEFAULT 0;
ALTER TABLE settings ADD COLUMN protein_goal INTEGER DEFAULT 150;
